In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
import sys
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

from nets import *
from cfgs import *
from data import *
from trainer import *

In [3]:
%matplotlib inline
save_plot = False
plt.rcParams.update({'font.size': 10, 'axes.labelsize': 'x-large'})
D = 1000

X_tst = np.random.rand(10000, 10)

cfg = additive_1x10_uniform_config.cfg
cfg.test.batch_size = D
cfg.test.num_batches = int(X_tst.shape[0]/cfg.test.batch_size)
cfg.test.save_output = True

In [4]:
Net = additive_net.Net
Generator = uniform_01_generator.Generator
Trainer = trainer.Trainer

In [5]:
net = Net(cfg, "test")
generator = Generator(cfg, 'test', X_tst)
m = Trainer(cfg, "test", net)
m.test(generator)

INFO:tensorflow:Restoring parameters from experiments/additive_1x10_uniform/model-400000


2019-01-30 01:53:07,732:INFO:Restoring parameters from experiments/additive_1x10_uniform/model-400000
2019-01-30 01:53:11,621:INFO:TEST BATCH-0: t = 3.8531, Net_Loss: -3.469761, Revenue: 3.469761
2019-01-30 01:53:11,631:INFO:TEST BATCH-1: t = 3.8587, Net_Loss: -3.418889, Revenue: 3.418889
2019-01-30 01:53:11,639:INFO:TEST BATCH-2: t = 3.8630, Net_Loss: -3.452765, Revenue: 3.452765
2019-01-30 01:53:11,647:INFO:TEST BATCH-3: t = 3.8670, Net_Loss: -3.463082, Revenue: 3.463082
2019-01-30 01:53:11,654:INFO:TEST BATCH-4: t = 3.8708, Net_Loss: -3.491514, Revenue: 3.491514
2019-01-30 01:53:11,661:INFO:TEST BATCH-5: t = 3.8746, Net_Loss: -3.473212, Revenue: 3.473212
2019-01-30 01:53:11,668:INFO:TEST BATCH-6: t = 3.8782, Net_Loss: -3.445038, Revenue: 3.445038
2019-01-30 01:53:11,675:INFO:TEST BATCH-7: t = 3.8817, Net_Loss: -3.468786, Revenue: 3.468786
2019-01-30 01:53:11,681:INFO:TEST BATCH-8: t = 3.8852, Net_Loss: -3.417095, Revenue: 3.417095
2019-01-30 01:53:11,688:INFO:TEST BATCH-9: t = 3.888

In [6]:
alloc = np.load(os.path.join(cfg.dir_name, "alloc_tst_" + str(cfg.test.restore_iter) + ".npy"))

In [7]:
X_tst[1512]

array([ 0.24364821,  0.47017804,  0.43674189,  0.67991505,  0.46059495,
        0.69579159,  0.57851872,  0.83044447,  0.65870802,  0.46688782])

In [14]:
alloc[0:100]

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        

In [21]:
alloc[0:10]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [30]:
alloc[63]

array([ 0.20348331,  0.17122349,  0.25193036,  0.79722738,  0.2032278 ,
        0.17525424,  0.25702462,  0.18401787,  0.79392797,  0.28569603])

In [31]:
X_tst[63]

array([ 0.09082491,  0.3218047 ,  0.67961406,  0.98158328,  0.02229074,
        0.16858181,  0.50795676,  0.13207324,  0.8655105 ,  0.11738772])

In [ ]:
fig, ax = plt.subplots(ncols = 1, nrows = 1, figsize=(8,6))
img = ax.imshow(alloc[::-1, :, 0], extent=[0,4,0,3], vmin = 0.0, vmax=1.0, cmap = 'YlOrRd', aspect=4.0/3)
                    
#plt.text(5, 4.5, s='0', color='black', fontsize='10', fontweight='bold')
#plt.text(5.25, 6, s='0.5', color='black', fontsize='10', fontweight='bold')

ax.set_xlabel('$v_1$')
ax.set_ylabel('$v_2$')
plt.title('Prob. of allocating item 1')
plt.colorbar(img, fraction=0.046, pad=0.04)
if save_plot:
    fig.set_size_inches(4, 3)
    plt.savefig(os.path.join(cfg.dir_name, 'alloc1.pdf'), bbox_inches = 'tight', pad_inches = 0.05)

In [ ]:
fig, ax = plt.subplots(ncols = 1, nrows = 1, figsize=(8,6))
img = ax.imshow(alloc[::-1, :, 1], extent=[0,4,0,3], vmin = 0.0, vmax=1.0, cmap = 'YlOrRd', aspect=4.0/3)
                    
#plt.text(5, 4.5, s='0', color='black', fontsize='10', fontweight='bold')
#plt.text(5.25, 6, s='0.5', color='black', fontsize='10', fontweight='bold')

ax.set_xlabel('$v_1$')
ax.set_ylabel('$v_2$')
plt.title('Prob. of allocating item 2')
plt.colorbar(img, fraction=0.046, pad=0.04)
if save_plot:
    fig.set_size_inches(4, 3)
    plt.savefig(os.path.join(cfg.dir_name, 'alloc2.pdf'), bbox_inches = 'tight', pad_inches = 0.05)

In [2]:
import os, glob, shutil

In [4]:
files = glob.glob("experiments/*/*.pdf")

In [10]:
for i in range(len(files)):
    shutil.copy(files[i], files[i][12:].replace("/", "_"))